=== sbparkb/MicroStrategyPortal/core/WebContent/WEB-INF/xml/dtds/beanTask.dtd
<!--
	A beanTask element defines a single Task based on a Web Bean or a
	Web Component.
	1) A beanTask consists of a REQUIRED basicInfo, ZERO or MORE eventInfo
	   and a REQUIRED beanInfo element, in that order.  If NO eventInfo 
	   elements are specified, it is assumed that either no events need to 
	   be handled or the event to handle is selected dynamically. In latter 
	   case, a base class must be specified to programmatically select an 
	   event (or events) to process.
	2) A beanTask has an OPTIONAL 'registerAs' attribute that specifies
       the identifier for this Task. If omitted, it is the base name
       of the file that contains the Task definition.
	3) A beanTask has an OPTIONAL 'class' attribute which specifies the
	   base class for this implementation. If set, it must be a subclass
	   of WebComponentTask. If omitted, then WebComponentTask is used.
-->
<!ELEMENT beanTask (basicInfo, eventInfo*, beanInfo)>
<!ATTLIST beanTask registerAs NMTOKEN #IMPLIED>
<!ATTLIST beanTask adminTask (true | false) "false">
<!ATTLIST beanTask class NMTOKEN #IMPLIED>
<!ATTLIST beanTask deleted NMTOKEN #IMPLIED>
<!ATTLIST beanTask privileges CDATA #IMPLIED>

<!--
	A basicInfo element defines the "metadata" for this Task.
	1) A basicInfo element can contain ZERO or MORE parameter elements.
	   Each parameter element declares a parameter of the Task. It is 
	   encouraged to declare all parameters as this makes the interface
	   to the Task very clear and explicit. In this way, changes to the
	   underlying event (e.g., its arguments) can be shielded from the 
	   user of the Task. 
	2) A basicInfo element has an OPTIONAL 'desc' attribute to provide
	   a textual description for the Task.
-->
<!ELEMENT basicInfo (parameter*)>
<!ATTLIST basicInfo desc CDATA #IMPLIED>

<!--
	A parameter element defines the metadata for a single Task parameter.
	1) A parameter element does not allow any children.
	2) A parameter element has a REQUIRED 'name'. Parameters names should
	   URL friendly identifiers.
	3) A parameter element has an OPTIONAL 'desc' (textual description)
	   attribute.
	4) A parameter element has an OPTIONAL 'required' parameter which
	   conveys whether the specified parameter is required for the Task
	   to work properly. If omitted, it is assumed to not be required.
	5) A parameter element has an OPTIONAL 'defvalue' attribute which 
	   specifies a "default value". If the parameter is not included
	   in the Task invocation, the default value is supplied. This is 
	   not the same as a parameter which has an empty value. In this case,
	   the default value is not applied. This allows the Task designer
	   to distinguish between non-existent and empty parameters.
-->
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter name NMTOKEN #REQUIRED>
<!ATTLIST parameter desc CDATA #IMPLIED>
<!ATTLIST parameter required (true | false) "false">
<!ATTLIST parameter defvalue CDATA #IMPLIED>
<!ATTLIST parameter deleted NMTOKEN #IMPLIED>
<!ATTLIST parameter type NMTOKEN #IMPLIED>
<!ATTLIST parameter validator NMTOKEN #IMPLIED>
<!ATTLIST parameter hidden (true | false) "false">
<!ATTLIST parameter type NMTOKEN #IMPLIED>
<!ATTLIST parameter validator NMTOKEN #IMPLIED>

<!--
	An eventInfo element specifies an underlying Event that implements
	the "data collection" portion of this Task.
	1) An eventInfo element contains ZERO or MORE argument elements.
	2) An eventInfo element has a REQUIRED 'eventID' attribute which is
	   the numeric identifier for the event. 
-->
<!ELEMENT eventInfo (argument*)>
<!ATTLIST eventInfo eventID NMTOKEN #REQUIRED>
<!ATTLIST eventInfo deleted NMTOKEN #IMPLIED>

<!--
	An argument element specifies the assignment or handling of a single
	event argument. This is provided as a way to define how values are
	assigned to event arguments. Not all event arguments need to be 
	declared here, especially if they are optional or not overridden.
	1) An argument element may not contain any children.
	2) An argument element has a REQUIRED 'name' attribute. It refers to
	   the name of the event argument.
	3) An argument element has a REQUIRED 'value' attribute. This is used
	   to compute a value to for the event argument. How it is interpreted
	   is controlled by the next attribute ('source').
	4) An argument element has an OPTIONAL 'source' attribute. This 
	   defines how 'value' should be interpreted. If 'source' is 'const',
	   then the value is a constant value and assigned directly.
	   If 'source' is 'parameter', then 'value' is really a parameter
	   name, whose value should be used instead. This allows a Task
	   designer to present a clear, understandable interface
	   (in terms of the declared parameters) and map the values
	   of those parameters to event arguments, style names, and actual
	   parameter values. If omitted, 'const' is assumed.
-->
<!ELEMENT argument EMPTY>
<!ATTLIST argument name NMTOKEN #REQUIRED>
<!ATTLIST argument value CDATA #REQUIRED>
<!ATTLIST argument source (const | parameter) "const">
<!ATTLIST argument deleted NMTOKEN #IMPLIED>

<!-- 
	A beanInfo element specifies the underlying Web Bean (or Web Component) 
	that is created to handle this Task.
	1) A beanInfo element has ZERO or ONE style children. A style element
	   represents a style in the Style Catalog.
	2) A beanInfo element has an OPTIONAL 'name' property which is the
	   name to apply to the bean instance (via setName).
	3) A beanInfo element has an OPTIONAL 'bean-type' property which
	   identifies the bean to instantiate. Examples include "ReportBean",
	   "FolderBean" and others. See EnumSysBeanNames for a list of valid
	   values. If omitted, an "empty" Bean object is used. It returns no data,
	   but can be used with any transform.
-->
<!ELEMENT beanInfo (style?)>
<!ATTLIST beanInfo name NMTOKEN #IMPLIED>
<!ATTLIST beanInfo bean-type NMTOKEN #IMPLIED>

<!--
	A style element defines a style in the Style Catalog and (through the
	use of the actualParameter element) how actual parameters are
	overridden.
	1) A style element has ZERO or MORE actualParameter children.
	2) A style element has a REQUIRED 'name' attribute to specify the
	   name of the style in the catalog. How this name is interpreted is
	   controlled by the next attribute ('source').
	3) A style element has an OPTIONAL 'source' attribute which specifies
	   how this name is interpreted. If 'source' is 'const' then 'name' is
	   the actual name of the style in the style catalog. If 'source' is
	   'parameter', then 'name' is the name of a Task parameter. The value
	   of this parameter is the actual style name used. If omitted,
	   'source' is assumed to be 'const'.
-->
<!ELEMENT style (actualParameter*)>
<!ATTLIST style name NMTOKEN #REQUIRED>
<!ATTLIST style source (const | parameter) "const">
<!ATTLIST argument deleted NMTOKEN #IMPLIED>

<!--
	An actualParameter element represents the assignment of a single
	actual parameter when the style (and associated transform) is
	instantiated.
	1) An actualParameter element does not allow any children.
	2) An actualParameter element has a REQUIRED 'name' attribute.
	3) An actualParameter element has a REQUIRED 'value' attribute. How it
	   is interpreted depends on the 'source' attribute.
	4) An actualParameter element has an OPTIONAL 'source' attribute. If
	   'source' is 'const', then the 'value' attribute is a constant 
	   value assigned directly. If 'source' is 'parameter', then 'value'
	   is the name of a Task parameter. The value of this parameter is
	   assigned instead. If omitted, 'source' is assumed to be
	   'const'.
-->
<!ELEMENT actualParameter EMPTY>
<!ATTLIST actualParameter name NMTOKEN #REQUIRED>
<!ATTLIST actualParameter value CDATA #REQUIRED>
<!ATTLIST actualParameter source (const | parameter) "const">
<!ATTLIST actualParameter deleted NMTOKEN #IMPLIED>

=== sbparkb/MicroStrategyPortal/spring/src/main/webapp/WEB-INF/xml/beanTasks/createGroup.xml
<!DOCTYPE beanTask SYSTEM "../dtds/beanTask.dtd">
<beanTask class="com.microstrategy.web.app.tasks.CreateGroupTask" privileges="EnableAdministrationFromWeb">
	<basicInfo desc="This Task provides the ability to create user group. Includes the ability to set the basic parameters for user group. For setting multiple parameters, we use caret to seperate them.">
		<!-- parameter for create event -->
		<parameter name="parents" desc="The parent id of the group to create" required="false" />
		<parameter name="description" desc="The description of the group to create" required="false" />
		<parameter name="groupName" desc="The full name of the group to create" required="true" />
		<parameter name="children" desc="The children of the group to create"  required="false" />
	</basicInfo>
	<!--
		"32768008" is the EnumUserEntityBeanEvents.USER_ENTITY_EVENT_INIT_AS_NEW.
	-->
	<eventInfo eventID="32768008">
	</eventInfo>
	
	<!--
		"32768001" is the EnumUserEntityBeanEvents.USER_ENTITY_EVENT_MODIFY_BASIC.
	-->
	<eventInfo eventID="32768001">	
		<argument name="fullName" value="groupName" source="parameter"  />
		<argument name="saveNow" value="1" />
	</eventInfo>
	
	<!--
		"8192001" is the EnumGroupBeanEvents.GROUP_EVENT_MODIFY_CHILDREN.
	-->
	<eventInfo eventID="8192001">
	</eventInfo>
	
	<!--
		"32768007" is the EnumUserEntityBeanEvents.USER_ENTITY_EVENT_SAVE.
	-->
	<eventInfo eventID="32768007">	
	</eventInfo>
	
	<!--
		This information describes how the task is defined in terms of an existing
		Bean.  The name of the bean is 'ugb' (to be able to restore the bean state from request). 
	-->
	<beanInfo name="ugb" bean-type="UserGroupBean">
	</beanInfo>
</beanTask>

=== sbparkb/MicroStrategyPortal/spring/src/main/webapp/WEB-INF/xml/beanTasks/loadDocLayout.xml
<!DOCTYPE beanTask SYSTEM "../dtds/beanTask.dtd">
<beanTask class="com.microstrategy.web.app.tasks.LoadDocLayoutTask">
	<!-- 
		This Task is used to load the layout of a Report Writer document.
	-->
	<basicInfo desc="This Task loads the specified layout of a Report Writer document.">
		<parameter name="layoutKey" desc="Specifies the key of the layout to load." required="true" />
		<parameter name="rwb" desc="The state of the Report Writer Bean." required="true" type="simplestring"/>
        <parameter name="groupByIDs" desc="List of desired GroupBy IDs" required="false" type="simplestring"/>
		<parameter name="availableWidth"
			desc="The width of the available screen area. Used in the MicroStrategy Mobile app when document layout zoom type is fit to width or fit to page."
			required="false" defvalue="0" type="int"/>
        <parameter name="availableHeight"
            desc="The height of the available screen area. Used in the MicroStrategy Mobile app when document layout is optimized for micro-app and zoom type is fit to page."
            required="false" defvalue="0" type="int"/>
        <parameter name="styleName"
            desc="The style to use when generating the data for this layout"
            required="false"
            defvalue="RWDocumentMojoStyle" type="simplestring"/>
	</basicInfo>

	<!-- REPORT_WRITER_EVENT_SET_CURRENT_LAYOUT -->
	<eventInfo eventID="2048093">
		<argument name="sectionKey" value="layoutKey" source="parameter" />
	</eventInfo>
	
	<!--
		This information describes how the task is defined in terms of an existing Bean.
	-->
	<beanInfo name="rwb" bean-type="RWBean">
		<style name="styleName" source="parameter">
			<actualParameter name="treesToRender" source="const" value="3" />
            <actualParameter name="availableWidth" value="availableWidth" source="parameter" />
            <actualParameter name="availableHeight" value="availableHeight" source="parameter" />
		</style>
	</beanInfo>
</beanTask>

=== sbparkb/MicroStrategyPortal/spring/src/main/webapp/WEB-INF/xml/beanTasks/searchMetadata.xml
<!DOCTYPE beanTask SYSTEM "../dtds/beanTask.dtd">
<beanTask class="com.microstrategy.web.app.tasks.MetadataSearchTask">
	<!-- 
		This information is used to provide "metadata" about this task. In general, it includes
		names, descriptions and whether the parameters are required or not. 
	-->
	<basicInfo desc="This Task provides the ability to search MicroStrategy Metadata. Includes the ability to perform incremental fetch.">
		<parameter name="styleName" desc="The style to use to transform the FolderBean." defvalue="WidgetFolderStyle" required="false" type="simplestring"/>
		<!-- parameter for browsing, support incremental fetch and sorting -->
		<parameter name="blockBegin" desc="The index (starting at 1) of the first element to begin browsing.  If omitted, then the first element is chosen." required="false" />
		<parameter name="blockCount" desc="The number of elements to return in this fetch.  If omitted, then all remaining elements are returned." required="false" />
		<parameter name="sortKey" desc="How the elements of the folder are sorted. Sort keys are specified as integers, as described by the EnumWebObjectSort interface.  If omitted, then WebObjectSortObjectNameFoldersFirst is used ('6') is used." required="false" type="simplestring"/>
		<parameter name="asc" desc="Whether elements of the list are sorted in ascending order or not.  Values are either 'true' or 'false'.  If omitted, then 'true' is assumed." required="false" type="boolean"/>
		<!-- parameter for search event -->
		<parameter name="searchID" desc="Specifies the ID of the search to use." required="false" />
		<parameter name="searchPattern" desc="Specifies the text that the name should include in the search." required="false" />
		<parameter name="nameWildcards" desc="Specifies whether the search will include wildcards." required="false" />
		<parameter name="rootFolderID" desc="Specifies the ID of the root folder." required="false" />
		<parameter name="rootFolderType" desc="Specifies the type of the root folder." required="false" />
		<parameter name="objectType" desc="Specifies the types of the objects to search within the list of validObjectTypes." required="false" />
		<parameter name="dateType" desc="Specifies if the search should be restricted based on the date." required="false" />
		<parameter name="dateSubType" desc="Specifies if the search should be restricted based on dates on a time or date interval." required="false" />
		<parameter name="created" desc="Specifies if the search should be restricted based on dates taken from the creation time." required="false" />
		<parameter name="intervalUnit" desc="Specifies the time units when a search is restricted based on a time interval." required="false" />
		<parameter name="intervalValue" desc="Specifies the time value when a search is restricted based on a time interval." required="false" />
		<parameter name="startDate" desc="Specifies the starting date when a search is restricted based on a date interval." required="false" />
		<parameter name="endDate" desc="Specifies the ending date when a search is restricted based on a date interval." required="false" />
		<parameter name="ownerType" desc="Specifies the owner of the object to search." required="false" />
		<parameter name="description" desc="Specifies to restrict the search based on some text found in the description." required="false" />
		<parameter name="maxObjects" desc="Specifies whether the search should return a maximum number of objects." required="false" />
		<parameter name="recursive" desc="Specifies whether to recurse into the subfolders during a search operation. Set argument to 1 to enable recursion." required="false" />
		<parameter name="searchDomain" desc="Specifies an integer value for the search domain. It defaults to com.microstrategy.webapi.EnumDSSXMLSearchDomain #DssXmlSearchDomainProject." required="false" />
		<parameter name="folderBrowserStyle" desc="Specifies whether the search should perform in a folder browsing style. In folder browsing style, the subfolders in current root folder will be automatically added as search result when the search has a root and not recursive." required="false"/>
		<parameter name="includeAncestorInfo" desc="Specifies whether the Block should include ancestor information." required="false" type="boolean"/>
		<parameter name="dataSourcesXML" desc="Specifies the data sources xml to be used by the search" required="false"/>
		<parameter name="includeObjectDesc" desc="Indicates whether it is need to output object description." required="false" type="boolean"/>
        <parameter name="folderLinksContextId" desc="Specifies the context id associated with the folder links that appear on the ancestor list." required="false" type="int"/>
        <parameter name="quickSearch" desc="Specifies whether to use New Search Engine." required="false"/>
        <parameter name="fields" desc="Specifies what fields to search - name, description or comment." required="false"/>
		<parameter name="validObjectTypes" desc="What subtype of objects we want to limit the output to. A comma-separated list of values from EnumDSSXMLObjectSubTypes. This parameter can only be modified via the searchMetadata.xml file." required="false" defvalue="1,2,3,4,8,10,11,12,13,14,18,39,43,47,55,72,256,257,512,768,769,770,771,772,773,774,775,776,778,779,1024,1025,1026,1027,1028,2048,2560,2566,2567,2568,2569,3072,3328,3585,3587,12032,14080,14081,14082,17153" hidden="true"/>
		<parameter name="showObjectTags" desc="Indicates whether we need to provide object tags" required="false" defvalue="false" type="boolean"/>
		<parameter name="uses" desc="Specifies the object info to be used to search dependent. Format: did:type" required="false" />
		<parameter name="includeHiddenAncestors" desc="Hidden ancestor should be included" defvalue="false" required="false" type="boolean" />
	</basicInfo>

	<!--
		This information describes how the task is defined in terms of an existing 
		Event.  "2003" is the EnumFolderBeanEvents.FOLDER_EVENT_SEARCH Event.
	-->
	<eventInfo eventID="2003">
		<argument name="usePreviousRootFolder" value="1"/>
		<argument name="folderBlockBegin" value="blockBegin" source="parameter"  />
		<argument name="folderBlockCount" value="blockCount" source="parameter"  />
		<argument name="recurse" value="recursive" source="parameter"  />
		<argument name="dataSources" value="dataSourcesXML" source="parameter"  />
		<argument name="name" value="searchPattern" source="parameter"  />
		<argument name="quickSearch" value="quickSearch" source="parameter"  />
	</eventInfo>
	
	<eventInfo eventID="2001">	
		<argument name="folderBlockBegin" value="blockBegin" source="parameter"  />
		<argument name="folderBlockCount" value="blockCount" source="parameter"  />
	</eventInfo>
	
	<!--
		This information describes how the task is defined in terms of an existing
		Bean.  The name of the bean is 'fb' (to be able to restore the bean state from request). 
	-->
	<beanInfo name="fb" bean-type="FolderBean">
        <style name="styleName" source="parameter">		
			<!-- Override the actual parameters associated with this style with values
			     from URL (or form data) parameters.
            -->

            <actualParameter name="sortField" value="sortKey" source="parameter" />
            <actualParameter name="sortAscending" value="asc" source="parameter"  />
            <actualParameter name="includeOwnerInfo" value="false"/>
            <actualParameter name="includeTimeInfo" value="false"/>
            <actualParameter name="includeAncestorInfo" value="includeAncestorInfo" source="parameter" />
			<actualParameter name="includeObjectDesc" value="includeObjectDesc" source="parameter" />
            <actualParameter name="folderLinksContextId" value="folderLinksContextId" source="parameter"/>
            <actualParameter name="showObjectTags" value="showObjectTags" source="parameter"/>
            <actualParameter name="searchPattern" value="searchPattern" source="parameter"/>
            <actualParameter name="includeHiddenAncestors" value="includeHiddenAncestors" source="parameter"/>
		</style>

	</beanInfo>
</beanTask>

=== sbparkb/MicroStrategyPortal/spring/src/main/webapp/WEB-INF/xml/beanTasks/getServerJSONResults.xml
<!DOCTYPE beanTask SYSTEM "../dtds/beanTask.dtd">
<beanTask class="com.microstrategy.web.app.tasks.GetServerJSONResultsTask">
	<!-- 
		This information is used to provide "metadata" about this task. In
		general, it includes names, descriptions and whether the parameters
		are required or not.
	-->
	<basicInfo
		desc="This Task provides the ability to transform a report with the style specified on the request keys as 'styleName'.">
		<parameter name="styleName" desc="The style to use to transform the RWBean. If omitted, a simple MessageResult is generated." required="false" type="simplestring"/>
		<parameter name="rwb" desc="The state of the RWBean" required="false" type="simplestring"/>
		<parameter name="messageID" desc="The Message ID of a previously executed Document." required="false" />
		<parameter name="availableWidth" desc="The width of the available screen area. Used in the MicroStrategy Mobile app when document layout zoom type is fit to width or fit to page." required="false" defvalue="0" type="int"/>
        <parameter name="availableHeight" desc="The height of the available screen area. Used in the MicroStrategy Mobile app when document layout is optimized for micro-app and zoom type is fit to page." required="false" defvalue="0" type="int"/>
        <parameter name="executionMode" desc="The parameter to specify the execution mode to run the document. See EnumRWExecutionModes for details." required="false" />
        <parameter name="params" desc="The JSON containing parameters" required="false" />
    </basicInfo>	

	<!-- run rwd event -->
	<eventInfo eventID="2048001" >
    </eventInfo>
	
	<!--
		This information describes how the task is defined in terms of an
		existing Bean.
	-->
	<beanInfo name="rwb" bean-type="RWBean">
		<style name="styleName" source="parameter">
			<actualParameter name="availableWidth" value="availableWidth" source="parameter" />
           	<actualParameter name="availableHeight" value="availableHeight" source="parameter" />
           	<actualParameter name="treesToRender" source="const" value="3" />
            <actualParameter name="resFlags" value="resFlags" source="parameter" />
		</style>
	</beanInfo>
</beanTask>

=== sbparkb/MicroStrategyPortal/core/WebContent/WEB-INF/xml/beanTasks/unsetSelector.xml
<!DOCTYPE beanTask SYSTEM "../dtds/beanTask.dtd">
<beanTask class="com.microstrategy.web.app.tasks.RWManipulationTask">

	<basicInfo desc="To change the unset state of a selector, send the unitKeyContext or the controlKey">
		<parameter name="unitKeyContext" desc="" required="false" />
        <parameter name="ctlKey" desc="" required="false" />
        <parameter name="zoomFactor" desc="Zoom factor of the document" required="false" type="float" />
	</basicInfo>	

	<!-- rwUnsetSelectorControl event  -->
	<eventInfo eventID="2048128"/>
	
	<!--
		This information describes how the task is defined in terms of an existing
		Bean.
	-->
	<beanInfo name="rwb" bean-type="RWBean">
        <style name="RWDocumentMojoStyle">
            <actualParameter name="treesToRender" source="const" value="2" />
            <actualParameter name="zoomFactor" value="zoomFactor" source="parameter"/>
        </style>
    </beanInfo>
</beanTask>

=== sbparkb/MicroStrategyPortal/spring/src/main/webapp/WEB-INF/xml/beanTasks/browseHierarchy.xml
<!DOCTYPE beanTask SYSTEM "../dtds/beanTask.dtd">
<beanTask>
	<!-- 
		This information is used to provide "metadata" about this task. In general, it includes
		names, descriptions and whether the parameters are required or not. 
	-->
	<basicInfo desc="This Task provides the ability to browse down to an attribute or element in a hierarchy based on browse path. Includes the ability to perform searching and incremental fetch.">
		<!-- parameter for browsing, support incremental fetch and searching -->
		<parameter name="browsePath" desc="Specifies the browse path in the hierarchy. check EnumDataExplorerBeanEvents.DATA_EXPLORER_EVENT_ARGUMENT_BROWSE_PATH for how to construct the browse path." required="true"/>
		<parameter name="searchPattern" desc="Specifies the search pattern." required="false"/>
		<parameter name="matchCase" desc="Specifies whether the search should be performed with case sensitive or not." required="false"/>
		<parameter name="blockBegin" desc="Specifies the blockBegin property for incremental fetch." required="false"/>
		<parameter name="blockCount" desc="Specifies the blockCount property for incremental fetch." required="false"/>
		<parameter name="dataSourcesXML" desc="Specifies the data sources xml to be used by the search" required="false" />
		<parameter name="latlng" desc="Specifies the latitude and longitude for the search" required="false" /> 
		<parameter name="isPathEncoded" desc="Specifies if we have encoded the browsepath at clientside or not" required="false" />
		<parameter name="messageID" desc="Specifies the messageID" required="false" />
	</basicInfo>

	<!--
		This information describes how the task is defined in terms of an existing 
		Event. "4104003" is the EnumDataExplorerBeanEvents.DATA_EXPLORER_EVENT_BROWSE_WITH_PATH Event.
	-->
	<eventInfo eventID="4104003">
		<argument name="dataSources" value="dataSourcesXML" source="parameter"  />
	</eventInfo>
	
	<!--
		This information describes how the task is defined in terms of an existing
		Bean.  The name of the bean is 'deb'. 
	-->
	<beanInfo name="deb" bean-type="DataExplorerBean">	
		<!-- Add a style called 'WidgetDataExplorerStyle' to this bean. -->
		<style name="WidgetDataExplorerStyle" />
	</beanInfo>
</beanTask>

=== sbparkb/MicroStrategyPortal/spring/src/main/webapp/WEB-INF/xml/beanTasks/RWDataService.xml
<!DOCTYPE beanTask SYSTEM "../dtds/beanTask.dtd">
<beanTask class="com.microstrategy.web.app.tasks.RWDataServiceTask">
	<!-- 
		This information is used to provide "metadata" about this task. In general, it includes
		names, descriptions and whether the parameters are required or not. 
	-->
	<basicInfo desc="This Task provides the ability to login, transform a document with the style specified by the caller and logout.">
		<parameter name="styleName" desc="The style to use to transform the RWBean" required="true" type="simplestring"/>
		<parameter name="rwb" desc="The state of the RWBean" required="false" type="simplestring"/>
		<parameter name="objectID" desc="The object ID of the Document to execute." required="false" />
		<parameter name="messageID" desc="The Message ID of a previously executed Report" required="false" />
		<parameter name="gridsResultFlags" desc="The results flags that apply to all grids in the document. See EnumDSSXMLResultFlags for details." required="false" />
		<parameter name="execFlags" desc="The execution flags to use. See EnumDSSXMLDocExecutionFlags for details." required="false" />
	</basicInfo>	

	<!-- run rwd event -->
	<eventInfo eventID="2048001" />
	
	<!--
		This information describes how the task is defined in terms of an existing bean.
	-->
	<beanInfo name="rwb" bean-type="RWBean"/>
</beanTask>

=== sbparkb/MicroStrategyPortal/spring/src/main/webapp/WEB-INF/xml/beanTasks/applyGraphSelectorAction.xml
<!DOCTYPE beanTask SYSTEM "../dtds/beanTask.dtd">
<beanTask class="com.microstrategy.web.app.tasks.RWManipulationTask">
	<!-- 
		This information is used to provide "metadata" about this task. In general, it includes
		names, descriptions and whether the parameters are required or not. 
	-->
	<basicInfo desc="This task sets current elements for control on graph.">
		<parameter name="messageID" desc="The Message ID of a previously executed Report Writer Document." required="false" type="guid"/>
		<parameter name="selectorKeyContext" desc="The key context of the Selector Control. It may be a simple key for the control or a key with tree type and node type (all separated by ITEM_SEPARATOR)." required="true" />
		<parameter name="targetList" desc="A list of target keys separated by the ITEM_SEPARATOR (see EnumRWBeanEvents for details)." required="false"/>
        <parameter name="sliceID" desc="Graph slice ID" required="true"/>
        <parameter name="x" desc="Cursor X coordinate." required="true"/>
        <parameter name="y" desc="Cursor Y coordinate" required="true"/>
        <parameter name="ctrlKeys" desc="A list of control keys separated by the ITEM_SEPARATOR (see EnumRWBeanEvents for details)." required="false"/>
		
	</basicInfo>	

	<!-- REPORT_WRITER_EVENT_APPLY_GRAPH_CONTROL_ACTION -->
	<eventInfo eventID="2048082">
		<!-- argument name="usePartDisplay" source="const" value="1" /-->
		<argument name="unitKeyContext" source="parameter" value="selectorKeyContext" />
		<argument name="ctlTargetStr" source="parameter" value="targetList" />
	</eventInfo>
	
	<!--
		This information describes how the task is defined in terms of an existing
		Bean.
	-->
	<beanInfo name="rwb" bean-type="RWBean">
		<style name="RWDocumentMojoStyle">
			<actualParameter name="treesToRender" source="const" value="2" />
            <actualParameter name="zoomFactor" value="zoomFactor" source="parameter"/>
		</style>
	</beanInfo>
</beanTask>
